# Generated by Django 6.0.2 on 2026-02-27 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('experience', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('availableNow', models.BooleanField(default=True)),
                ('avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], max_length=20)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='app.worker')),
            ],
        ),
    ]
